version: "3.5"
services:
  jenkins:
    build: ./.docker
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-log:/var/log/jenkins
      - jenkins-home:/var/jenkins_home

volumes:
  jenkins-log:
  jenkins-home: